### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by odemeulder** [odemeulder/matrickandeve#15]
I moved the site away from shopify and back to the heroku site where we had it at first. 

The fonts appear not to load from typekit.

@KyleKrukar , could you take a look and see what's up?

**Comment by odemeulder** [comment]
It looks like you changed the font to Verdana, but it used to be future lt (through typekit i believe)

**Comment by KyleKrukar** [comment]
I 'removed' the code for verdana. I didn't add anything.

**Comment by odemeulder** [comment]
duh ... sorry about that.
